name: Pull request
on:
  pull_request:
jobs:
  check-build-push:
    name: Build and publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build
        run:
          mvn package -DskipTests
